// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDkaKwZsScTX3LVXZkNTNUtEMTefROmVs',
    appId: '1:269738785548:android:3dfea7d653f4ad17736729',
    messagingSenderId: '269738785548',
    projectId: 'up-ecomm',
    storageBucket: 'up-ecomm.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD23AOD6Uv9U4AtGuUfmSFhy7TsXCf_bsU',
    appId: '1:269738785548:ios:314c11af08ab6a27736729',
    messagingSenderId: '269738785548',
    projectId: 'up-ecomm',
    storageBucket: 'up-ecomm.firebasestorage.app',
    androidClientId: '269738785548-f6on85jf749jii7h62nn3kko08bku1t7.apps.googleusercontent.com',
    iosClientId: '269738785548-t164sq03srgceh5jtpfitejkr5c3j8fd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomm',
  );
}
